s0405/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/', include('app01.urls')),
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url, include
from web.views import account, home, project, wiki, file, settings, issues, dashboard,statistics

urlpatterns = [
    url(r'^register/$', account.register, name='register'),
    url(r'^api/send_msg/$', account.send_msg),
    url(r'^sms/login/$', account.sem_login, name='sms_login'),
    url(r'^login/$', account.login, name='login'),
    url(r'^api/code/$', account.login_code, name='api_code'),
    url(r'^index/$', home.index, name='index'),
    url(r'^logout/$', account.logout, name='logout'),
    url(r'^project/list/$', project.list_project, name='list_project'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),
    url(r'^price/$',home.price, name='price'),
    url(r'^payment/(?P<policy_id>\d+)/$', home.payment, name='payment'),
    url(r'^pay/$', home.pay, name='pay'),
    # 项目功能
    url(r'^manage/(?P<project_id>\d+)/', include([
        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),  # 项目详细页面
        url(r'^dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),
        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        url(r'^statistics/project/user/$', statistics.statistics_project_user, name='statistics_project_user'),
        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        url(r'^issues/update/(?P<issues_id>\d+)/$', issues.issues_update, name='issues_update'),
        url(r'^issues/detail/(?P<issues_id>\d+)/reply/$', issues.issues_reply, name='issues_reply'),
        url(r'^issues/invite/url/$', issues.issues_invite, name='issues_invite'),
        url(r'^setting/$', settings.setting, name='setting'),
        url(r'^setting/delete/$', settings.setting_delete, name='setting_delete'),
        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        url(r'^wiki/order/$', wiki.wiki_order, name='wiki_order'),
        url(r'^wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),
        url(r'^file/$', file.file, name='file'),
        url(r'^file/sts-cam/$', file.sts_cam, name='sts_cam'),
        url(r'^file/delete/$', file.file_delete, name='file_delete'),
        url(r'^file/file_add/$', file.file_add, name='file_add'),
        url(r'^file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download')
    ], None, None)),
    url(r'^invite/join/(?P<code>\w+)/', issues.invite_join, name='invite_join')

]

web/models.py
from django.db import models


# Create your models here.
from django.utils import timezone


class UserInfo(models.Model):
    """
    用户信息表
    """
    username = models.CharField(verbose_name='用户名', max_length=64)
    password = models.CharField(verbose_name='密码', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机', max_length=64)
    email = models.EmailField(verbose_name='邮箱', max_length=64)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "01-用户信息表"
        db_table = verbose_name
        verbose_name_plural = verbose_name


class PricePolicy(models.Model):
    """
    价格策略表
    """
    title = models.CharField(verbose_name='策略名称', max_length=64, null=True)
    category_choices = ((1, '免费版'), (2, '收费版'), (3, '其他'))
    category = models.SmallIntegerField(verbose_name='策略类型', choices=category_choices, default=1)
    price = models.PositiveIntegerField(verbose_name='价格')
    project_length = models.PositiveSmallIntegerField(verbose_name='创建项目个数')
    team_member = models.PositiveSmallIntegerField(verbose_name='项目成员个数')
    project_capacity = models.IntegerField(verbose_name='项目空间', help_text='GB')
    single_file_capacity = models.IntegerField(verbose_name='单文件最大容量', help_text='MB')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "02-价格策略表"
        db_table = verbose_name
        verbose_name_plural = verbose_name


class OrderRecord(models.Model):
    """
    交易记录表
    """
    status_choice = ((0, '未支付'), (1, '已支付'))
    status = models.IntegerField(choices=status_choice, verbose_name='交易状态')
    order = models.CharField(verbose_name='订单号', max_length=64, unique=True, null=True)
    user = models.ForeignKey(to='UserInfo', verbose_name='该交易关联的用户')
    price = models.ForeignKey(to='PricePolicy', verbose_name='该交易关联的价格策略')
    count = models.SmallIntegerField(verbose_name='数量(年)', help_text='0表示无期限', default=0)
    actual_payment = models.IntegerField(verbose_name='实际支付价格', null=True, blank=True)
    start_time = models.DateTimeField(verbose_name='订单生成时间', null=True, blank=True)
    pay_time = models.DateTimeField(verbose_name='付款时间', null=True, blank=True)
    end_time = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    class Meta:
        verbose_name = "03-交易记录表"
        db_table = verbose_name
        verbose_name_plural = verbose_name


class Project(models.Model):
    """
    项目表
    """
    color_choice = (
        (1, "#56b8eb"),  # 56b8eb
        (2, "#f28033"),  # f28033
        (3, "#ebc656"),  # ebc656
        (4, "#a2d148"),  # a2d148
        (5, "#20BFA4"),  # #20BFA4
        (6, "#7461c2"),  # 7461c2,
        (7, "#20bfa3"),  # 20bfa3,)
    )

    name = models.CharField(verbose_name='项目名称', max_length=64)
    color = models.SmallIntegerField(choices=color_choice, verbose_name='颜色', default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.BigIntegerField(verbose_name='项目已使用空间', default=0, help_text='字节B')
    star = models.BooleanField(verbose_name='星标项目', default=False)
    join_count = models.SmallIntegerField(verbose_name='参与项目人数', default=1)
    creator = models.ForeignKey(to='UserInfo', verbose_name='项目创建者')
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')
    bucket = models.CharField(verbose_name='cos桶', max_length=128)
    region = models.CharField(verbose_name='cos区域', max_length=32)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "04-项目表"
        db_table = verbose_name
        verbose_name_plural = verbose_name


class ProjectUser(models.Model):
    """
    项目与参与者关系表
    """
    user = models.ForeignKey(to='UserInfo', verbose_name='项目参与者')
    project = models.ForeignKey(to='Project', verbose_name='参与的项目')
    star = models.BooleanField(verbose_name='星标项目', default=False)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='参与项目时间')

    class Meta:
        verbose_name = "05-项目参与表"
        db_table = verbose_name
        verbose_name_plural = verbose_name


class Wiki(models.Model):
    """项目功能之wiki功能的数据库"""
    title = models.CharField(verbose_name='wiki标题', max_length=128)
    content = models.TextField(verbose_name='wiki内容')
    project = models.ForeignKey(to='Project', verbose_name='属于哪个项目')
    parent = models.ForeignKey(to='self', verbose_name='选择父wiki', null=True, blank=True)
    depth = models.IntegerField(verbose_name='深度', default=1)

    class Meta:
        verbose_name = '06-项目的wiki表'
        db_table = verbose_name
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class PorjectFile(models.Model):
    """项目之文件的表"""
    title = models.CharField(verbose_name='文件夹名称', max_length=128)
    project = models.ForeignKey(to='Project', verbose_name='关联的项目')
    parent = models.ForeignKey(to='self', verbose_name='属于哪个文件', null=True, blank=True)
    file_type_choice = ((1, '文件夹'), (2, '文件'))
    file_type = models.SmallIntegerField(verbose_name='文件类型', choices=file_type_choice, default=1)
    file_capacity = models.IntegerField(verbose_name='文件大小', null=True, blank=True)
    file_path = models.CharField(max_length=255, verbose_name='文件url', null=True, blank=True)
    key = models.CharField(verbose_name='COS中的名称', max_length=128, null=True, blank=True)
    update_user = models.ForeignKey(to='UserInfo', verbose_name='更新者')
    update_datetime = models.DateTimeField(auto_now=True, verbose_name='更新者')

    class Meta:
        verbose_name = '07-项目的文件表'
        db_table = verbose_name
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Issues(models.Model):
    """项目问题表"""
    project = models.ForeignKey(to='Project', verbose_name='关联的项目')
    title = models.CharField(max_length=64, verbose_name='问题标题')
    desc = models.TextField(verbose_name='问题描述')
    issues_type = models.ForeignKey(to='IssuesType', verbose_name='问题属于哪个类型')
    issues_model = models.ForeignKey(to='IssuesModel', verbose_name='问题属于哪个模块', null=True, blank=True)
    status_choice = (
        (1, '处理中'),
        (2, '已解决'),
        (3, '新建'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.IntegerField(choices=status_choice, verbose_name='问题状态', default=1)
    # 使用字符串是为了在前端中可以和类名进行拼接
    level_choice = (('success', '普通'), ('warning', '紧急'), ('danger', '非常紧急'))
    level = models.CharField(choices=level_choice, max_length=12, verbose_name='问题优先级', default='danger')

    assign = models.ForeignKey(to='UserInfo', verbose_name='问题指派', null=True, blank=True, related_name='issues_assign')
    attention = models.ManyToManyField(to='UserInfo', verbose_name='问题关注者', blank=True, related_name='issues_attention')
    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)
    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)




class IssuesType(models.Model):
    """问题类型表"""
    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']
    name = models.CharField(max_length=32, verbose_name='问题类型')
    project = models.ForeignKey(to='Project', verbose_name='关联的项目')

    class Meta:
        verbose_name = '09-问题表的类型表'
        db_table = verbose_name
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class IssuesModel(models.Model):
    """问题的模块(里程碑)"""
    name = models.CharField(max_length=32, verbose_name='问题模块')
    project = models.ForeignKey(to='Project', verbose_name='关联的项目')

    class Meta:
        verbose_name = '10-问题表的里程碑表'
        db_table = verbose_name
        verbose_name_plural = verbose_name


class IssuesReply(models.Model):
    """问题评论、操作记录表"""
    reply_type_choice = (
        (1, '操作记录'),
        (2, '回复'),
        (3, '评论')
    )
    reply_type = models.IntegerField(choices=reply_type_choice, verbose_name='类型')
    issues = models.ForeignKey(to='Issues', verbose_name='问题')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(to='UserInfo', verbose_name='创建者')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_reply = models.ForeignKey(to='self', verbose_name='父评论', null=True, blank=True)

    class Meta:
        verbose_name = '11-问题的评论表'
        db_table = verbose_name
        verbose_name_plural = verbose_name


class ProjectInvite(models.Model):
    """项目邀请码"""
    project = models.ForeignKey(to='Project', verbose_name='关联的项目')
    code = models.CharField(verbose_name='邀请码', max_length=128)
    count = models.IntegerField(verbose_name='邀请码限制人数', null=True, blank=True, help_text='空则表示无限制人数')
    user_count = models.IntegerField(verbose_name='已邀请人数', default=0)
    period_choices = ((30, '30分钟'),
                      (60, '1小时'),
                      (300, '5小时'),
                      (1440, '24小时')
                      )
    period = models.IntegerField(choices=period_choices, verbose_name='邀请码有效期', default=1440)
    creator = models.ForeignKey(to='UserInfo', verbose_name='创建者')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    class Meta:
        verbose_name = '12-项目邀请码表'
        db_table = verbose_name

web/forms/wiki.py
from web.forms.bootstrap import BootStrapForm
from django import forms

from web.models import Wiki


class WikiModelForm(BootStrapForm, forms.ModelForm):

    def __init__(self, request, *args, **kwargs):
        first_choice = [('', '-------')]
        super().__init__(*args, **kwargs)
        # self.request = request
        wiki_queryset = Wiki.objects.filter(project=request.tracer.project).values_list('id', 'title')
        first_choice.extend(wiki_queryset)
        self.fields['parent'].choices = first_choice

    class Meta:
        model = Wiki
        exclude = ['project', 'depth']


class WikiEditModelForm(BootStrapForm, forms.ModelForm):
    """编辑wiki的form"""

    def __init__(self, request, wiki_id, *args, **kwargs):
        first_choice = [('', '-------')]
        super().__init__(*args, **kwargs)
        wiki_queryset = Wiki.objects.filter(project=request.tracer.project).exclude(id=wiki_id).values_list('id',
                                                                                                            'title')
        first_choice.extend(wiki_queryset)
        self.fields['parent'].choices = first_choice

    class Meta:
        model = Wiki
        exclude = ['project', 'depth']

web/views/dashboard.py
import datetime
import time

import collections
from django.db.models import Count
from django.http import JsonResponse

from web import models

from django.shortcuts import render


def dashboard(request, project_id):
    """概览首页"""

    # 问题数据处理
    status_dict = collections.OrderedDict()
    for key, text in models.Issues.status_choice:
        status_dict[key] = {'text': text, 'count': 0}

    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    # 项目成员
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    # 最近的10个问题
    top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[0:10]
    print('top_ten', top_ten)

    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten_object': top_ten
    }
    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    """ 在概览页面生成highcharts所需的数据 """
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]


    result = models.Issues.objects.filter(project_id=project_id,
                                          create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))

    print('result', result)
    for item in result:
        date_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

web/views/settings.py
from django.shortcuts import render, redirect

from utils.Tencent.Cos import delete_bucket
from web.models import PorjectFile, Project


def setting(request, project_id):
    return render(request, 'settings.html')


def setting_delete(request, project_id):
    print(request.POST)
    if request.method == 'GET':
        return render(request, 'setting_delete.html')
    project_title = request.POST.get('setting_delete', '')

    if not project_title or project_title != request.tracer.project.name:
        return render(request, 'setting_delete.html', {'error': '项目名错误'})

    if request.tracer.user != request.tracer.project.creator:
        return render(request, 'setting_delete.html', {'error': '只能删除自己的项目'})

    # 通过校验，进行删除
    delete_bucket(request.tracer.project.bucket)
    # 删除数据库
    Project.objects.filter(name=project_title, creator=request.tracer.user).delete()
    return redirect('list_project')

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block title %}
    首页
{% endblock %}

{% block content %}
<div>
    <img src="{% static 'web/img/index/index-1.png' %}">
    <img src="{% static 'web/img/index/index-2.png' %}">
    <img src="{% static 'web/img/index/index-3.png' %}">
    <img src="{% static 'web/img/index/index-4.png' %}">
</div>
{% endblock %}

web/templates/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}
    加入项目
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <h4><i class="fa fa-check-circle" aria-hidden="true"></i>{{ error }}</h4>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i>加入成功</h4>
                <a href="{% url 'dashboard' project_id=project.id %}"></a>

            </div>
        {% endif %}
    </div>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}
    短信登陆
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            font-size: 13px;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">登陆</div>
        <form method="post" novalidate id="smsLogin">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {% if field.label == '验证码' %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <input type="button" id="send_code" class="btn btn-primary" value="点击获取验证码">
                            </div>
                        </div>
                    {% else %}

                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>


                    {% endif %}
                </div>
            {% endfor %}
            <div>
                <div style="float: right;">
                    <a href="{% url 'login' %}">账号密码登陆</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <button type="button" class="btn btn-success" id="btnSubmit">登陆</button>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

{% block js %}
    <script>


        $('#send_code').click(function () {
            let send_phone = $("input[name=mobile_phone]").val();

            var obj = $('#send_code');


            $.ajax({
                url: '/api/send_msg',
                data: {mobile_phone: send_phone, tpl: 'login'},
                type: 'GET',
                success: function (data) {
                    if (data.status) {
                        settime(obj);

                        console.log(data);

                    }
                    else {
                        //将错误信息渲染到span标签上

                        $.each(data.error, function (k, v) {
                            $('#id_' + k).next().text(v[0])
                        });

                        {#$('#id_mobile_phone').next().text(data.error.mobile_phone[0])#}
                    }

                }
            })
        });
        $('#btnSubmit').click(function () {
            $('.error-msg').empty();
            $.ajax({
                url:'/sms/login/',
                type:'post',
                dataType: 'JSON',
                data: $('#smsLogin').serialize(),  // 获取form中的所有字段+csrf_token
                success:function (res) {
                    if (res.status){
                        console.log(res);
                        location.href = res.data
                    }
                    else {
                        $.each(res.error, function (k, v) {
                            $('#id_'+ k).next().text(v[0])
                        })
                    }

                }
            })
        });


        var countdown = 60;

        function settime(obj) {
            if (countdown == 0) {
                obj.attr('disabled', false);
                obj.val('再次获取验证码');
                countdown = 60;
                return
            }
            else {
                obj.attr('disabled', true);  // 开启disabled，input框无法编辑
                obj.val("重新发送(" + countdown + ")");
                countdown = countdown - 1;
            }
            // setTimeout方法在函数内部使用，每隔1秒自动调用自己函数
            setTimeout(function () {
                settime(obj)
            }, 1000)
        }


    </script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% block title %}
    项目管理
{% endblock %}



{% block css %}
    <style>
        .projects {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        {#让input不显示#}
        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }

    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid projects">
        <div style="margin: 10px 0;">
            <a class="btn btn-primary" id="add_project"><i class="fa fa-plus-circle" aria-hidden="true"></i>添加项目</a>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标项目</div>
            <div class="panel-body">
                {% for star_project in user_project_dict.star %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=star_project.value.id %}" class="title"
                           style="background-color: {{ star_project.value.get_color_display }};">{{ star_project.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=star_project.type project_id=star_project.value.id %}"><i
                                        class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i></a>
                                <span>{{ star_project.value.creator }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span></span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-list" aria-hidden="true"></i> 我创建的项目
            </div>
            <div class="panel-body">
                {% for my_project in user_project_dict.my %}
                    {#                    <div class="col-sm-6 col-md-3">#}
                    {#                        <div class="thumbnail">#}
                    {#                            <div class="caption">#}
                    {#                                <h3>{{ my_project.name }}</h3>#}
                    {#                                <p>...</p>#}
                    {#                                <p>{{ my_project.creator }}</p>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=my_project.id %}" class="title"
                           style="background-color: {{ my_project.get_color_display }};">{{ my_project.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='my' project_id=my_project.id %}"><i
                                        class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i></a>
                                <span>{{ my_project.creator }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span></span>
                            </div>
                        </div>
                    </div>
                {% endfor %}


            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的项目
            </div>
            <div class="panel-body">
                {% for join_project in user_project_dict.join %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=join_project.id %}" class="title"
                           style="background-color: {{ join_project.get_color_display }};">{{ join_project.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='join' project_id=join_project.id %}"><i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i></a>
                                <span>{{ join_project.creator }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span></span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <! -- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }} <span class="error-msg"></span>
                            </div>

                        {% endfor %}


                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="btnSubmit">创建</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        $('#add_project').click(function () {
            $('#myModal').modal('toggle')
        });
        $('#btnSubmit').click(function () {
            $.ajax({
                url: "{% url 'list_project' %}",
                data: $('#addForm').serialize(),
                type: 'post',
                dataType: 'JSON',
                success: function (res) {
                    console.log(status);
                    if (res.status) {
                        location.reload()
                    }
                    else {
                        $.each(res.error, function (k, v) {
                            $('#id_' + k).next().text(v[0])
                        })
                    }

                }
            })

        })

    </script>
{% endblock %}